### ISSUE TITLE
Segmentation error on Ubuntu 16.10

### ISSUE THREAD

**Issue by kwon-young** [franapoli/lglc#2]
When compiling on ubuntu 16.10, the executable lglc crash with a segmentation error when run with the default samples/test.lf file.
Here's the stack trace:
```
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff7b76577 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocato
r<char> >::basic_string(char const*, std::allocator<char> const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000555555586b2c in Frame::doAction (this=0x5555557c1d40, type=ACT_NODE, p1=0x557c74c0,
    p2=0x0, p3=0x0, p4=0x0) at /home/kwon-young/prog/lglc/src/Frame.cpp:158
#3  0x000055555559c569 in yyparse () at lglc.yy:91
#4  0x00005555555897d8 in Frame::run (this=0x5555557c1fc0)
    at /home/kwon-young/prog/lglc/src/Frame.cpp:451
#5  0x000055555559a204 in CallStack::Run (this=0x5555557af480 <cs>)
    at /home/kwon-young/prog/lglc/src/CallStack.h:37
#6  0x0000555555599f54 in main (argc=2, argv=0x7fffffffd798)
    at /home/kwon-young/prog/lglc/src/main.cpp:134
```
For what i've could debug, there is a problem when parsing a leaf of the tree.
When parsing a leaf, the grammar execute the Frame::doAction method with a Linkable* pointer in parameter (should probably contains the leaf object).
However, no Linkable (or child class type) is allocated before executing doAction.
I couldn't resolve the problem because it seems that its coming from the grammar (and that's outside the scope of my poor competence)
Could you look into it ?
This project looks awesome by the way, and I would really like to use it for my dataflow !

**Comment by kwon-young** [comment]
never mind, i regenerated grammar files with bison and flex and it's working now
